### ISSUE TITLE
Doesn't work on Windows 11 Dev Channel Build 25905.1000 and 22631.2050

### ISSUE THREAD

**Issue by etomoinick** [hereafter/desktop-switch#15]
Hi, dev!

Since update Windows 11 Insider Preview 25905.1000 (rs_prerelease) icon in taskbar shows only "0".

**Comment by hereafter** [comment]
thanks for the heads-up．
Could be the API has been updated to a new version.

**Comment by hereafter** [comment]
My daily driver beta build is impacted too. 22631.2050
System popup labels for virtual desktops are introduced.

**Comment by hereafter** [comment]
display works on 22631.2050 migrating the notifications.


![Image](https://github.com/hereafter/desktop-switch/assets/1483954/a7dec7be-ee42-4aeb-a037-afb8fb61aa34)

**Comment by hereafter** [comment]
an update 1.6 has been posted to Microsoft Store.
Tested on x64 22631.2050 & 25905.1000

Should be available very soon.

**Comment by pmyers** [comment]
I can confirm that the latest update in the Microsoft Store did indeed resolve the issue. Thanks!!!
