### ISSUE TITLE
22635.2915, 22621.3078, 23615.1000 API changes make the app glitching

### ISSUE THREAD

**Issue by hereafter** [hereafter/desktop-switch#23]
Doesn't work on the latest beta version. The notification icon shows the number of the desktop that was active at startup. After restarting the application, the notification icon does not appear at all. Only the settings dialog.

![image](https://github.com/hereafter/desktop-switch/assets/737560/b38ed7c5-137a-456f-b27a-c30f6d49c4b5)

_Originally posted by @EvilX in https://github.com/hereafter/desktop-switch/discussions/13#discussioncomment-7925671_

**Comment by hereafter** [comment]
I have tested on the said build. It is not working
API changes. The same old story.
It is time to dump the new apis :/

**Comment by etomoinick** [comment]
Hi,

on **Windows 11 Insider Preview 23615.1000 (ni_prerelease)** tray icon does not change number of the virtual desktop.

**Comment by hereafter** [comment]
> Hi,
> 
> on **Windows 11 Insider Preview 23615.1000 (ni_prerelease)** tray icon does not change number of the virtual desktop.

happens on my daily driver 22621.3078 as well
a solution is tested on 22621.3078 22635.2915

I will try 23615 builds as well

**Comment by EvilX** [comment]
Works again 

![image](https://github.com/hereafter/desktop-switch/assets/737560/c8d112d3-c2f7-46b0-8306-550decf76cc8)

**Comment by hereafter** [comment]
23615 working
