### ISSUE TITLE
REQ: Use of Number Pad

### ISSUE THREAD

**Issue by Daggerfin** [hereafter/desktop-switch#4]
Could you also include the number pad numbers as part of the CTRL+WIN + # sequence?

Thanks for the beautiful app!

**Comment by tno-brimurray** [comment]
I agree, the ability to use keyboard number pad would be very usefull.

**Comment by hereafter** [comment]
feature request accepted

**Comment by hereafter** [comment]
please see coming update 1.4

https://github.com/users/hereafter/projects/4

**Comment by tno-brimurray** [comment]
> please see coming update 1.4
> 
> https://github.com/users/hereafter/projects/4

Just updated and working great.

Thank you hereafter.... such an essential app for my workflows>
