### ISSUE TITLE
REQ: Hotkey activation - WIN Key without CTRL

### ISSUE THREAD

**Issue by Daggerfin** [hereafter/desktop-switch#5]
Could you add a setting to make the hotkey sequence WIN + #?

The reasoning behind this is that it make one handed desktop switching easier and also doing so, as another benefit, would overwrite the task bar shortcut launcher hotkeys that can be an annoyance.

**Comment by hereafter** [comment]
It would conflict with taskbar shortcuts

**Comment by Daggerfin** [comment]
I wouldn't mind having the taskbar shortcuts disabled to make using virtual desktop simpler (currently I use WS Virtual Desktop Tool to do this, but would prefer a single package)
