### ISSUE TITLE
Doesn't work anymore with Windows 11

### ISSUE THREAD

**Issue by jemmail** [hereafter/desktop-switch#8]
The Tray icon show a "0" and then the app crash

**Comment by jemmail** [comment]
After your Update to Version 1.2.16.. it works like a charm for several months.

but now with Windows Version 22H2. Once again it show a "0" .. (but this time doesn't crash)

![image](https://user-images.githubusercontent.com/24605319/175953372-0b8c9b39-ee7f-4f6b-8970-5513b2ef0455.png)

**Comment by hereafter** [comment]
Noted, working on a patch

**Comment by hereafter** [comment]
https://github.com/users/hereafter/projects/4

Please see release 1.4 soon coming to the store
