### ISSUE TITLE
Will no longer start automatically

### ISSUE THREAD

**Issue by appquestions** [hereafter/desktop-switch#9]
I not sure what has changed... (possibly my security settings) but the app will no longer start up when booting up my computer. I need to manually start the app each time.

**Comment by hereafter** [comment]
Please go to "Task Manager" Startup Tab make sure the app is enabled for auto start

**Comment by appquestions** [comment]
Thank you :) for your help. It is disabled within the Startup Tab and when I try to enable it, it doesn't stick. :(

**Comment by hereafter** [comment]
It is hard to pin point the problem, could you please paste some screenshots and some more system infomration?

**Comment by appquestions** [comment]
The problem is fixed and for anyone reading this, please know that it had nothing to do with this outstanding Virtual Desktop App! 

After reading your reply I discovered that the Startup option was missing from the Windows 10 Apps settings. I suspect a Windows Update caused the problem. After reinstalling Windows 10 the issue was resolved. I am back to Desktop Switching Bliss! ;-) 

Thank you so much for your help and for creating such a time saving App. :-)

**Comment by hereafter** [comment]
thanks for the update
